// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEeo2ZKlsKonMKsbEv6AJLA_y83LaP5qA',
    appId: '1:297023446217:web:b6c79ee146edbdcc878118',
    messagingSenderId: '297023446217',
    projectId: 'xpenses-3a8a3',
    authDomain: 'xpenses-3a8a3.firebaseapp.com',
    storageBucket: 'xpenses-3a8a3.appspot.com',
    measurementId: 'G-DCJQD5TWYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB7eX3K8XZ6KqOkD9CPF8rLz2OC6UYRp4',
    appId: '1:297023446217:android:2a36fe98f5ed9e76878118',
    messagingSenderId: '297023446217',
    projectId: 'xpenses-3a8a3',
    storageBucket: 'xpenses-3a8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvYXNsqBVGHpcmnLKH0PEax3SZzmdlybM',
    appId: '1:297023446217:ios:8792b3a76195d461878118',
    messagingSenderId: '297023446217',
    projectId: 'xpenses-3a8a3',
    storageBucket: 'xpenses-3a8a3.appspot.com',
    iosClientId: '297023446217-ph8jdl9q8akqrtu5c3c0n9qbaufgf7ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpensesV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvYXNsqBVGHpcmnLKH0PEax3SZzmdlybM',
    appId: '1:297023446217:ios:8792b3a76195d461878118',
    messagingSenderId: '297023446217',
    projectId: 'xpenses-3a8a3',
    storageBucket: 'xpenses-3a8a3.appspot.com',
    iosClientId: '297023446217-ph8jdl9q8akqrtu5c3c0n9qbaufgf7ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpensesV2',
  );
}
